### ISSUE TITLE
Feature Request: Evoker's Boots/Carbuncle's Cuffs in SMN LUA

### ISSUE THREAD

**Issue by GensoXI** [yzyii/luashitacast#3]
Hi there,

Not an issue but i'm currently unable to use Discord, so apologies for posting this here.

Was curious if there was a way to implement the use of Evoker's Boots and Carbuncle's Cuffs in the SMN LUA? These items reduce casting time of summoning and don't affect general spells. Currently Fast Cast sets in the LUA affect all spells (of which Rostrum Pumps would take priority) so putting the mentioned two items in that section would be pointless.

Thank you for your time and the excellent work you've done!

**Comment by yzyii** [comment]
Added in 1.2.6 alongside some other stuff
