### ISSUE TITLE
Melee - Fenrir's Earring time constraint

### ISSUE THREAD

**Issue by Beo3o** [yzyii/luashitacast#4]
Time constraint for Fenrir's Earrring in `gcmelee.lua` seems to match any time

https://github.com/yzyii/luashitacast/blob/4c7d4c1d3352541f326369c2ddde9e4e1deb225e/common/gcmelee.lua#L89

https://github.com/yzyii/luashitacast/blob/4c7d4c1d3352541f326369c2ddde9e4e1deb225e/common/gcmelee.lua#L108

instead of  just daytime: `[6, 18)`

`environment.Time >= 6 and environment.Time < 18`

**Comment by yzyii** [comment]
Fixed in 1.3.8
