### ISSUE TITLE
Hide the /slash commands from printing to the chat window.

### ISSUE THREAD

**Issue by Mr-Sithel** [yzyii/luashitacast#6]
I've narrowed it down to when a profile loads and shows all those /slash commands my chat window will always wipe the window clean of all chat when I expand the window and go back.. Is there a way to hide those from printing to the chat window? Here's a pic of what I'm referring to when I change jobs.  Thanks!
![ffxi luashitcast](https://github.com/user-attachments/assets/5f756015-4bc2-49d9-bb1b-0e6f07dda867)

**Comment by yzyii** [comment]
This is not an issue with the lua.

You can change aliases.silent to 1 within the boot config to suppress alias messages. The file is located at: ..\Game\config\boot\ashita.ini

or you can change it within the in game /ashita menu
